### ISSUE TITLE
Construcción de la ventana1, primera parte

### ISSUE THREAD

**Issue by Wirkipe08** [Wirkipe08/Clase9#1]
Construir la ventana 1 y hacer el formulario para ingresar la información del cliente

**Comment by jjerito08** [comment]
Saludos, voy a encargarme de esta funcionalidad

**Comment by Wirkipe08** [comment]
Listo trabajo cumplido, porfavor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del ususario
