### ISSUE TITLE
Programar el botón para buscar las preguntas para recuperación de contraseña

### ISSUE THREAD

**Issue by Wirkipe08** [Wirkipe08/Clase9#6]
Validar que se ingrese el documento del usuario al cual se le va a buscar la contraseña 
Validar que el documento sea un dato tipo numérico
Crear la clase usuario con sus sus 11 propiedades
Solo considerar un password
Buscar las preguntas para recuperar la contraseña

**Comment by jjerito08** [comment]
Me voy a encargar de este issue, voy a desarrollarlo.
Pendiente de alguna sugerencia

**Comment by Wirkipe08** [comment]
Listo quedo pendiente de tu primer push y pull request

**Comment by jjerito08** [comment]
Se cierra este issue #6
